### PR TITLE
Add feeinfo()

### PR DESCRIPTION
**Pull request by zpalmtree**
Untested, probably works, lol.

Requires >= turtle-service-0.8.0

### CODE REVIEW

**Comment by timmcleod** [comment]
I didn't get a Github notification on this for some reason. Anyway, merged now.

**Comment by timmcleod** [comment]
@zpalmtree I was going to change the PHP method to `getInfo()` so that it was camel-cased like the others... but after looking at it, any objections to changing the PHP method to `getFeeInfo()`? The other methods are prefixed with `get`

**Comment by zpalmtree** [comment]
Yeah, ibmcd is a special snowflake and didn't name it camelCase. Feel free to change it however you like in your repo.

**Comment by brandonlehmann** [comment]
I'll give you a snowflake

**Comment by zpalmtree** [comment]
:kissing_heart:

**Comment by timmcleod** [comment]
Lol, nice, thanks

**Pull request merged**
